### ISSUE TITLE
大佬 有个兼容性的报错  换了很多版本不行

### ISSUE THREAD

**Issue by gr51** [zhaoyachao/zdh_server#11]
2024-07-25 18:23:35:720[INFO]: 开始初始化SparkSession
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:105)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.sql.SparkSession$.hiveClassesArePresent(SparkSession.scala:1117)
	at org.apache.spark.sql.SparkSession$Builder.enableHiveSupport(SparkSession.scala:866)
	at com.zyc.common.SparkBuilder$.initSparkSession(SparkBuilder.scala:34)
	at com.zyc.common.SparkBuilder$.getSparkSession(SparkBuilder.scala:44)
	at com.zyc.SystemInit$.main(SystemInit.scala:27)
	at com.zyc.SystemInit.main(SystemInit.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.2
	at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:174)
	at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:139)
	at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:100)
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:368)
	
	尝试了 hive切换为3.1.2也不行

**Comment by gr51** [comment]
具体的版本 spark 2.4.4 hive 2.3.9  hadoop 3.1.2

**Comment by zhaoyachao** [comment]
版本应该没有问题，猜测可能是你环境中有3.1.2的hadoop, 但是启动项目时使用的是项目自带的hadoop 2.x版本，尝试解决方案1 如果是本地idea开发，可尝试在pom文件中新增hadoop配置并指定和你环境相同的版本， 尝试解决方案2：环境中hadoop版调整至2.7.5 ，尝试解决方案3： 如果是通过spark-submit命令提交服务启动，则检查提交的hadoop版本是否和安装的hadoop版本一致

**Comment by zhaoyachao** [comment]
版本应该没有问题，猜测可能是你环境中有3.1.2的hadoop, 但是启动项目时使用的是项目自带的hadoop 2.x版本，尝试解决方案1 如果是本地idea开发，可尝试在pom文件中新增hadoop配置并指定和你环境相同的版本， 尝试解决方案2：环境中hadoop版调整至2.7.5 ，尝试解决方案3： 如果是通过spark-submit命令提交服务启动，则检查提交的hadoop版本是否和安装的hadoop版本一致

**Comment by gr51** [comment]
> 版本应该没有问题，猜测可能是你环境中有3.1.2的hadoop, 但是启动项目时使用的是项目自带的hadoop 2.x版本，尝试解决方案1 如果是本地idea开发，可尝试在pom文件中新增hadoop配置并指定和你环境相同的版本， 尝试解决方案2：环境中hadoop版调整至2.7.5 ，尝试解决方案3： 如果是通过spark-submit命令提交服务启动，则检查提交的hadoop版本是否和安装的hadoop版本一致

感谢大佬解惑  切换为2.7.5 成功了 记录一个问题 然后运行的是5.4.0分支 发现找不到redission hutool httpclient 然后把这三个包放到spark home下的jars目录启动成功  现在就是web服务 任务执行了 初始化完成  但是server端没有处理 有哪些原因啊
  一直卡到 
完成调整组任务调度时间6.5%

![微信截图_20240726143739](https://github.com/user-attachments/assets/299d5833-33f5-449f-8d3c-29979bd4e2aa)

**Comment by zhaoyachao** [comment]
web管理端》调度管理》调度器》系统任务列表，选择 【检查依赖任务】点击启用

**Comment by zhaoyachao** [comment]
web管理端》调度管理》调度器》系统任务列表，选择 【检查依赖任务】点击启用

**Comment by gr51** [comment]
![image](https://github.com/user-attachments/assets/247f2b90-41de-42b6-aa17-b6fa37115f88)
这种情况是否是没创建成功

**Comment by gr51** [comment]
> web管理端》调度管理》调度器》系统任务列表，选择 【检查依赖任务】点击启用

感谢大佬  刚才看了一下 要刷新一下redis缓存才会执行  大佬辛苦

**Comment by gr51** [comment]
感谢大佬指导&nbsp; 终于跑痛了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaoyachao/zdh_server] 大佬 有个兼容性的报错  换了很多版本不行 (Issue #11)




 
web管理端》调度管理》调度器》系统任务列表，选择 【检查依赖任务】点击启用
